### ISSUE TITLE
next.js 채팅 토이

### ISSUE THREAD

**Issue by DaehunGwak** [DaehunGwak/react-playground#30]
### TODO
- [x] 기술 조사 & 설계
- [ ] 세팅
- [ ] ui 구현
- [ ] api 형태 구현
- [ ] 기능 구현
  - [ ] polling
  - [ ] long-polling
  - [ ] server sent event
  - [ ] websocket
- [ ] 인프라 추가
- [ ] 인프라 추가 된 기능 반영

**Comment by DaehunGwak** [comment]
### 기술 조사
- RDB
  - planet scale(mysql) 은 무료티어 없음
  - supabase(postgresql) 무료티어 존재, 필요 시 사용
- remote queue
  - redis cloud 무료티어 존재
  - Kafka 까지는 사용하지 않아도 될듯?

### 설계
- 1차: next.js 만 사용 & 로컬 메모리만 사용
- 2차: next.js > redis pub/sub & postgresql (사용자 프로필 & 채팅방 검색 정도?)

### 스펙
- 사용자 프로필 (처음엔 uuid 로만 진행, 회원가입 생략, 이후 여유시간 될때 profile 편집 ㄱㄱ)
- 채팅방
- 채팅방 리스트
- 사용자 리스트
- 사용자 검색
